name: Backend CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - run: yarn
    - run: yarn workspace backend test
    - run: yarn workspace backend build